config/routes.rb
Rails.application.routes.draw do
  resources :transfers, only: [:index, :show]
end

app/models/admission.rb
class Admission < ApplicationRecord
  has_one :patient

  has_many :admission_diagnoses
  has_many :diagnoses, through: :admission_diagnoses

  has_many :admission_symptoms
  has_many :symptoms, through: :admission_symptoms

  has_many :admission_observations
  has_many :observations, through: :admission_observations
end

app/models/admission_diagnosis.rb
class AdmissionDiagnosis < ApplicationRecord
  belongs_to :admission
  belongs_to :diagnosis
end

app/models/admission_observation.rb
class AdmissionObservation < ApplicationRecord
  belongs_to :admission
  belongs_to :observation
end

app/models/admission_symptom.rb
class AdmissionSymptom < ApplicationRecord
  belongs_to :admission
  belongs_to :symptom
end

app/models/allergy.rb
class Allergy < ApplicationRecord
  has_many :patient_allergies
  has_many :patients, through: :patient_allergies
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diagnosis.rb
class Diagnosis < ApplicationRecord
  has_many :patient_diagnoses
  has_many :patients, through: :patient_diagnoses

  has_many :chronic_conditions, through: :patient_diagnoses, source: :diagnosis

  has_many :admissions_diagnoses
  has_many :admissions, through: :admission_diagnoses

  scope :chronic, -> { where(coding_system: 'CHRONIC') }
  scope :not_chronic, -> { where(coding_system: nil) }

  def display_name
    "#{description} (#{code})"
  end
end

app/models/diagnostic_procedure.rb
class DiagnosticProcedure < ApplicationRecord
  has_many :patient_diagnostic_procedures
  has_many :patients, through: :patient_diagnostic_procedures

  def display_name
    "#{description} on #{moment.to_formatted_s(:long).chop.chop.chop.chop.chop} at #{moment.strftime('%H:%M')}"
  end
end

app/models/facility.rb
class Facility < ApplicationRecord
end

app/models/medication_order.rb
class MedicationOrder < ApplicationRecord
  has_many :patient_medication_orders
  has_many :patients, through: :patient_medication_orders
  belongs_to :order_frequency

  enum route: [:po, :im, :sc]

  def display_name
    "#{name} #{dosage.round} #{route.upcase} #{order_frequency.value} to #{necessity}"
  end
end

app/models/observation.rb
class Observation < ApplicationRecord
  has_many :admissions_observations
  has_many :admissions, through: :admissions_observations
end

app/models/order_frequency.rb
class OrderFrequency < ApplicationRecord
end

app/models/patient.rb
class Patient < ApplicationRecord

  belongs_to :admission

  has_many :patient_allergies
  has_many :allergies, through: :patient_allergies

  has_many :patient_diagnoses
  has_many :diagnoses, through: :patient_diagnoses
  has_many :chronic_conditions, through: :patient_diagnoses, source: :diagnosis

  has_many :patient_diagnostic_procedures
  has_many :diagnostic_procedures, through: :patient_diagnostic_procedures

  has_many :patient_treatments
  has_many :treatments, through: :patient_treatments

  has_many :patient_medication_orders
  has_many :medication_orders, through: :patient_medication_orders

  enum gender: [:female, :male, :other]

  def age
    now = Time.now.utc.to_date
    now.year - dob.year - ((now.month > dob.month || (now.month == dob.month && now.day >= dob.day)) ? 0 : 1)
  end

  def medications
    medication_orders
  end
end

app/models/patient_allergy.rb
class PatientAllergy < ApplicationRecord
  belongs_to :patient
  belongs_to :allergy
end

app/models/patient_diagnosis.rb
class PatientDiagnosis < ApplicationRecord
  belongs_to :patient
  belongs_to :diagnosis
end

app/models/patient_medication_order.rb
class PatientMedicationOrder < ApplicationRecord
  belongs_to :patient
  belongs_to :medication_order
end

app/models/patient_treatment.rb
class PatientTreatment < ApplicationRecord
  belongs_to :patient
  belongs_to :treatment
end

app/models/symptom.rb
class Symptom < ApplicationRecord
  has_many :admissions_symptoms
  has_many :admissions, through: :admissions_symptoms
end

app/models/treatment.rb
class Treatment < ApplicationRecord
  has_many :patient_treatments
  has_many :patients, through: :patient_treatments
end

app/controllers/transfers_controller.rb
class TransfersController < ApplicationController

  def index
    @patients = Patient.all
  end

  def show
    @facility = Facility.first

    unless params[:id].blank?
      @patient = Patient.where(id: params[:id]).first
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/transfers/index.erb
<div class="title row"><h2>Emergency Transfer Patients</h2></div>

<br />

<div class="content row">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Patient</th>
        <th>Admission</th>
      </tr>
    </thead>

    <tbody>
      <% @patients.each do |p| %>
        <tr>
          <td>
            <%= link_to "#{p.first_name} #{p.middle_name} #{p.last_name}", transfer_path(p) %>
          </td>

          <td><%= p.admission.moment %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/transfers/show.erb
<div class="content row">
  <%= link_to 'Back', transfers_path %>
  <a href="#" onclick="window.print();return false;">print</a>
</div>

<div class="content row">
  <table class="table table-bordered">
      <tr class="summary-header"><td colspan="4"><h3>Emergency Transfer Summary (Form 34L-D)</h3></td></tr>

      <tr><td colspan="4"><b>Transferring Facility</b></td></tr>
      <tr>
        <td colspan="1">Name<br />
          <span style="color: #0000ff"><%= @facility.name %> </span><br /><br /><br />
        </td>
        <td colspan="3">&nbsp;</td>
      </tr>

      <tr>
        <td colspan="4"><b>Patient Information</b></td>
      </tr>

      <tr>
        <td>First Name<br />
          <span style="color: #0000ff"><%= @patient.first_name %></span>
        </td>

        <td>Middle Name<br /><br />
          <span style="color: #0000ff"><%= @patient.middle_name %></span>
        </td>

        <td>Last Name<br />
          <span style="color: #0000ff"><%= @patient.last_name %></span>
        </td>

        <td>Medical Record (MR)<br />
          <span style="color: #0000ff"><%= @patient.mr %></span>
        </td>
      </tr>

      <tr>
        <td colspan="4"><br /><b>Summary</b>
          <br />
          This <span style="color: #0000ff"><%= @patient.age %></span>
          years old <span style="color: #0000ff"><%= @patient.gender %></span>
          was admitted to <span style="color: #0000ff"><%= @facility.name %></span> emergency facility
          on <span style="color: #0000ff"><%= @patient.admission.moment.to_formatted_s(:long).chop.chop.chop.chop.chop %></span>
          at <span style="color: #0000ff"><%= @patient.admission.moment.strftime('%H:%M') %></span>
          due to <span style="color: #0000ff"><%= @patient.admission.diagnoses.map(&:display_name).to_sentence %></span>.

          The observed symptoms on admission were
          <span style="color: #0000ff"><%= @patient.admission.symptoms.map(&:description).to_sentence %></span>.

          <span style="color: #0000ff"><%= @patient.admission.observations.map(&:description).to_sentence %></span>.
          <br /><br />
          Upon asking about known allergies, the patient disclosed
          <span style="color: #0000ff"><%= @patient.allergies.map(&:description).to_sentence %></span>.

          Upon asking about chronic conditions, the patient disclosed
          <span style="color: #0000ff"><%= @patient.diagnoses.chronic.map(&:display_name).to_sentence %></span>.

          The patient was administered with
          <span style="color: #0000ff"><%= @patient.medication_orders.map(&:display_name).to_sentence %></span>.

          <br /><br />
          The staff performed
          <span style="color: #0000ff"><%= @patient.diagnostic_procedures.map(&:display_name).to_sentence %></span>.

          revealing
          <span style="color: #0000ff"><%= @patient.diagnoses.not_chronic.map(&:display_name).to_sentence %></span>.

          Our team proceeded to
          <span style="color: #0000ff"><%= @patient.treatments.first.description %> to <%= @patient.treatments.first.necessity %></span>.
          </span>
        </td>
      </tr>
  </table>
</div>